swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints related to transactions
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions:
    get:
      tags:
        - Transaction Module
      summary: Get All Transactions
      description: API to retrieve all transactions for the current month
      parameters:
        - in: query
          name: userId
          type: string
          description: ID of the user whose transactions are requested
          required: true
        - in: query
          name: month
          type: string
          description: Month for which transactions are to be retrieved (e.g., "2024-08")
          required: false
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '400':
          description: Invalid parameters
        '500':
          description: Internal Server Error
    post:
      tags:
        - Transaction Module
      summary: Create a new transaction
      description: API for adding a new transaction
      parameters:
        - in: body
          name: body
          description: Transaction Payload
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '201':
          description: Transaction created successfully
        '400':
          description: Invalid input data
        '500':
          description: Internal Server Error

  /transactions/{transactionId}:
    get:
      tags:
        - Transaction Module
      summary: Get Transaction Details
      description: API to retrieve details of a specific transaction
      parameters:
        - in: path
          name: transactionId
          type: string
          description: ID of the transaction to retrieve
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            $ref: '#/definitions/Transaction'
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    put:
      tags:
        - Transaction Module
      summary: Update a transaction
      description: API for modifying an existing transaction
      parameters:
        - in: path
          name: transactionId
          type: string
          description: ID of the transaction to update
          required: true
        - in: body
          name: body
          description: Updated transaction data
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
        '400':
          description: Invalid input data
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Transaction Module
      summary: Delete a transaction
      description: API for deleting a transaction
      parameters:
        - in: path
          name: transactionId
          type: string
          description: ID of the transaction to delete
          required: true
      produces:
        - application/json
      responses:
        '204':
          description: Transaction deleted successfully
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier for the transaction
      userId:
        type: string
        description: User ID associated with the transaction
      date:
        type: string
        format: date
        description: Date of the transaction
      description:
        type: string
        description: Description of the transaction
      category:
        type: string
        description: Category of the transaction (e.g., Food, Shopping, etc.)
      amount:
        type: number
        format: float
        description: Amount of the transaction
      type:
        type: string
        enum: [credit, debit]
        description: Type of the transaction (credit or debit)
      notes:
        type: string
        description: Notes or comments on the transaction

  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
        description: Updated category of the transaction
      notes:
        type: string
        description: Updated notes or comments on the transaction
      amount:
        type: number
        format: float
        description: Updated transaction amount

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          description:
            type: string
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
